### ISSUE TITLE
[🐛 Bug] requests.exceptions.TooManyRedirects: Exceeded 30 redirects

### ISSUE THREAD

**Issue by small-bili** [Harry-Jing/nonebot-plugin-bing-chat#18]
cookies文件应该是没有问题的（复制了三次），在本地粘贴后上传到服务器。
运行环境：python3.10，Ubuntu22.04
日志文件如下

03-06 22:12:32 [DEBUG] nonebot | Checking for matchers in priority 1...
 03-06 22:12:32 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bing_chat.common.utils)
03-06 22:12:32 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_bing_chat.common.utils)
03-06 22:12:32 [DEBUG] nonebot | Running handler Dependent(call=bing_chat_command_chat)
03-06 22:12:37 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
03-06 22:12:37 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bing_chat.common.utils) running complete
03-06 22:12:37 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bing_chat.common.utils) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/nonebot_plugin_bing_chat/onebotv11/main.py", line 59, in bing_chat_command_chat
    raise exc
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/nonebot_plugin_bing_chat/onebotv11/main.py", line 54, in bing_chat_command_chat
    current_user_data.chatbot = Chatbot(
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/EdgeGPT.py", line 269, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/EdgeGPT.py", line 178, in __init__
    response = self.session.get(
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/root/SLEXCE/QQlinux/enjoy/.venv/lib/python3.10/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
03-06 22:12:37 [DEBUG] nonebot | Stop event propagation

**Comment by Harry-Jing** [comment]
请尝试打开bing.com/chat获取Cookies，而非bing.com的Cookies

**Comment by citydirector** [comment]
用edge打开这个网页来复制ck
https://www.bing.com/search?q=Bing+AI&showconv=1

**Comment by Harry-Jing** [comment]
在 v0.6.0-alpha.4 中修复

**Comment by small-bili** [comment]
感谢
