### ISSUE TITLE
直接回复机器人的消息会报错

### ISSUE THREAD

**Issue by AlexZhou1995** [Harry-Jing/nonebot-plugin-bing-chat#32]
我一直使用/chat命令可以正常对话，但是长按bot消息点击回复，则会报错。报错信息如下：

```
Traceback (most recent call last):
  File "/home/user_me/workspace/bot/Alice/bot.py", line 17, in <module>
    nonebot.run()
  File "/home/user_me/workspace/bot/Alice/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/home/user_me/workspace/bot/Alice/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 187, in run
    uvicorn.run(
  File "/home/user_me/workspace/bot/Alice/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/user_me/workspace/bot/Alice/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/user_me/miniconda3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/user_me/workspace/bot/Alice/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/bot.py", line 190, in handle_event
    await _check_reply(self, event)
> File "/home/user_me/workspace/bot/Alice/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/bot.py", line 34, in _check_reply
    event.reply = Reply.parse_obj(await bot.get_msg(message_id=msg_seg.data["id"]))
  File "/home/user_me/workspace/bot/Alice/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
  File "/home/user_me/workspace/bot/Alice/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/home/user_me/workspace/bot/Alice/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 132, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "/home/user_me/workspace/bot/Alice/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(data=None, echo='17', msg='MSG_NOT_FOUND', retcode=100, status='failed', wording='消息不存在')
```

**Comment by Harry-Jing** [comment]
看起来像是gocq的问题（？

**Comment by AlexZhou1995** [comment]
> 

刚才去gocq搜了下，确实有人遇到了类似的问题，不过解决方法目前还不确定，谢谢，这里这个应该可以close了
