### ISSUE TITLE
Chatbot.__init__() got an unexpected keyword argument 'cookie_path'

### ISSUE THREAD

**Issue by Misaka13514** [Harry-Jing/nonebot-plugin-bing-chat#72]
version: 0.7.11

logs:

```
05-24 20:04:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bing_chat.common)
05-24 20:04:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bing_chat.common)
05-24 20:04:45 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bing_chat.common) running complete
05-24 20:04:45 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bing_chat.common) running complete
05-24 20:04:45 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bing_chat.common) failed.
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 98, in run
    return asyncio.run(self._serve())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/local/lib/python3.11/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.11/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/usr/local/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/lib/python3.11/site-packages/nonebot_plugin_bing_chat/onebotv11/main.py", line 101, in bingchat_command_chat
    raise exc
  File "/usr/local/lib/python3.11/site-packages/nonebot_plugin_bing_chat/onebotv11/main.py", line 95, in bingchat_command_chat
    current_user_data.chatbot = Chatbot(
TypeError: Chatbot.__init__() got an unexpected keyword argument 'cookie_path'
```

**Comment by TwindsCn** [comment]
请问您的问题得到解决了吗？我遇到了一个与您一模一样的报错

**Comment by Misaka13514** [comment]
@TwindsCn 降级 EdgeGPT 到 0.2.x

**Comment by Yuimi-chaya** [comment]
纯新手，想问一下怎么降级，球球大佬QAQ

**Comment by Misaka13514** [comment]
@LTDKRRRR 假设你正在使用pip

```
pip install EdgeGPT==0.2.1
```

**Comment by Yuimi-chaya** [comment]
> 

谢谢大佬

**Comment by TwindsCn** [comment]
> @TwindsCn 降级 EdgeGPT 到 0.2.x

谢谢，解决了。顺便问下大佬。在私聊模式中，是不是不能通过回复bot的消息继续对话，但在群聊中可以。

**Comment by Misaka13514** [comment]
> 在私聊模式中，是不是不能通过回复bot的消息继续对话，但在群聊中可以。

我这里测试是这样的，你可以开一个新issue。
